apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ocp-fio-master
  namespace: ocp-fio
spec:
  selector:
    matchLabels:
      app: ocp-fio-master
  template:
    metadata:
      labels:
        app: ocp-fio-master
    spec:
      serviceAccountName: default
      volumes:
      - hostPath:
        path: /tmp
        type: Directory
        name: host
      - name: fio-config-vol
        configMap:
          name: fio-job-config
      hostPID: true
      hostIPC: true
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - operator: Exists
      containers:
      - name: iostat
        volumeMounts:
        - mountPath: /host
          name: host
        - name: fio-config-vol
          mountPath: /configs
        image: quay.io/cloud-bulldozer/etcd-perf
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        command: ["/bin/sh"]
        args: ["-c", "while true; do fio --rw=write --ioengine=sync --fdatasync=1 --directory=/var/lib/etcd --size=100m --bs=8000 --name=etcd_perf --output-format=json --runtime=60 --time_based=1; done"]
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
